import type { Metadata } from "next";
import "./globals.css";
import "./navigationHub.css";
import { ToastProvider } from '@/components/common/Toast';

export const metadata: Metadata = {
  title: "Traffic Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <ToastProvider>
          {children}
      </ToastProvider>
      </body>
    </html>
  );
}
