import type {Metadata} from "next";
import "./globals.css";
import "./navigationHub.css";
import {ToastProvider} from '@/components/common/Toast';
import {AppProviders} from "@/providers/AppProvider";

export const metadata: Metadata = {
    title: "Traffic Page",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
        <body className={`antialiased`}>
        <AppProviders>
            <ToastProvider>
                {children}
            </ToastProvider>
        </AppProviders>
        </body>
        </html>
    );
}
